In [19]:
import torch

x = torch.randn(2,3)
print(x.shape)
print('data\n ',x)

x = x[:,-1]
print(x.shape)
print('data \n ',x)
print('data \n ',x.unsqueeze(-1))

torch.Size([2, 3])
data
  tensor([[-1.1371, -0.8429, -0.0223],
        [-0.9559,  0.3130,  0.0076]])
torch.Size([2])
data 
  tensor([-0.0223,  0.0076])
data 
  tensor([[-0.0223],
        [ 0.0076]])
