In [1]:
import numpy as np

# hello-numpy
## 1.1 创建numpy

In [25]:
score = np.array([
    [1,3,4,5],
    [5,6,7,8],
    [44,56,23,23]
])

score

array([[ 1,  3,  4,  5],
       [ 5,  6,  7,  8],
       [44, 56, 23, 23]])

# 1.2 ndarray和原生Python效率对比

In [11]:
import random
import time
import numpy as np

a=[]
for i in range(100000):
    a.append(random.random())

# %time魔法方法，可以查看当前代码运行一次花费时间
%time sum1=sum(a)

b = np.array(a) #转换成np数组
%time sum2 = np.sum(b)


CPU times: user 822 µs, sys: 0 ns, total: 822 µs
Wall time: 837 µs
CPU times: user 994 µs, sys: 215 µs, total: 1.21 ms
Wall time: 990 µs


# ndarray的使用
## 数组的属性


In [14]:
score

array([[ 1,  3,  4,  5],
       [ 5,  6,  7,  8],
       [44, 56, 23, 23]])

In [29]:
# 显示数组的形状，比如3行5列，3行2列等
score.shape

(3, 4)

In [17]:
# 数组的维数，比如2维数组，3维数组等
score.ndim

2

In [18]:
# 数组中元素的个数
score.size

12

In [28]:
# 数组中每个元素的字节长度
score.itemsize

8

In [27]:
# 数组元素的类型
score.dtype

dtype('int64')

## 2.2数组的形状

In [40]:
# 一维数组
# 在这个一维数中有3个元素
a = np.array([1,2,3])
a
a.shape

(3,)

In [41]:
# 二维数组
# 在这个二维数组中，有4个一位数组；每个一位数组中有3个元素
b = np.array([[1,2,3],[4,5,6],[4,5,6],[4,5,6]])
b
b.shape

(4, 3)

In [42]:
# 三维数组
# 在这个三维数组里，有5个二维数组；每个二位数组中各有2个一位数组；每个一维数组中各有3个元素
c = np.array([
    [[1,2,3],[4,5,6]],
    [[1,2,3],[4,5,6]],
    [[1,2,3],[4,5,6]],
    [[1,2,3],[4,5,6]],
    [[1,2,3],[4,5,6]]
])
c
c.shape

(5, 2, 3)

## 2.3 数组的类型

In [47]:
# 指定数组中元素的 numpy类型为32位浮点数
b = np.array([[1,2,3],[4,5,6],[4,5,6],[4,5,6]], dtype=np.float32)
b

array([[1., 2., 3.],
       [4., 5., 6.],
       [4., 5., 6.],
       [4., 5., 6.]], dtype=float32)

In [49]:
# 字符串类型数组
c = np.array(['fdsfd', "hello"], dtype=np.string_)
c

array([b'fdsfd', b'hello'], dtype='|S5')