# 1 Series
## 1.1 Series创建 pd.Series(data=None,index=None, dtype=None)
* data 对应的数据列表
* index 列表对应的索引

In [3]:
import pandas as pd
import numpy as np

In [5]:
# 创建一个series数据
pd.Series(np.arange(10))

0    0
1    1
2    2
3    3
4    4
5    5
6    6
7    7
8    8
9    9
dtype: int64

In [6]:
# 创建指定索引的Series数据
pd.Series([1.2,1.2,3.9,5.1],index=[1,2,3,4])

1    1.2
2    1.2
3    3.9
4    5.1
dtype: float64

In [9]:
color_count = pd.Series({"red":10,"green":20,"blude":100})
color_count

red       10
green     20
blude    100
dtype: int64

In [12]:
# 通过默认索引获取数据
color_count[1]

20

In [14]:
# 通过指定的索引获取数据?
color_count['green']

20

# 1.2 series属性

In [15]:
color_count.index #索引

Index(['red', 'green', 'blude'], dtype='object')

In [16]:
color_count.values #数据值

array([ 10,  20, 100])

# 2 DataFrame 类似二维数组对象
## pd.DataFrame(data=,index=,colums=)
* data
* index 行索引
* columns 列索引

## 2.1  DataFrame创建

In [19]:
pd.DataFrame(np.random.randn(2,3)) #randn() 从标准正态分布中获取数据，然后弄成2行3列

0         1         2
0 -0.904028  0.735452 -1.795189
1  1.445621  2.178581 -0.143101

In [21]:
# 从40~100中取数据，组成10行5列的数据
score = np.random.randint(40,100,(10,5))
score

array([[44, 62, 53, 74, 56],
       [40, 90, 70, 59, 46],
       [60, 63, 50, 95, 43],
       [58, 43, 69, 96, 48],
       [78, 51, 71, 54, 57],
       [44, 62, 71, 61, 49],
       [96, 68, 99, 59, 79],
       [95, 49, 88, 89, 69],
       [74, 70, 45, 45, 66],
       [92, 54, 88, 82, 51]])

In [23]:
score_df = pd.DataFrame(score)
score_df

0   1   2   3   4
0  44  62  53  74  56
1  40  90  70  59  46
2  60  63  50  95  43
3  58  43  69  96  48
4  78  51  71  54  57
5  44  62  71  61  49
6  96  68  99  59  79
7  95  49  88  89  69
8  74  70  45  45  66
9  92  54  88  82  51

In [35]:
subjects = ['语文','数学','英语','政治','体育']
stu = ["同学"+str(i) for i in range(score_df.shape[0])]
data = pd.DataFrame(score,index=stu,columns=subjects)
data

语文  数学  英语  政治  体育
同学0  44  62  53  74  56
同学1  40  90  70  59  46
同学2  60  63  50  95  43
同学3  58  43  69  96  48
同学4  78  51  71  54  57
同学5  44  62  71  61  49
同学6  96  68  99  59  79
同学7  95  49  88  89  69
同学8  74  70  45  45  66
同学9  92  54  88  82  51

## 2.2 DataFrame的属性


In [36]:
#看形状
data.shape

(10, 5)

In [37]:
#看行索引
data.index

Index(['同学0', '同学1', '同学2', '同学3', '同学4', '同学5', '同学6', '同学7', '同学8', '同学9'], dtype='object')

In [38]:
#看列索引
data.columns

Index(['语文', '数学', '英语', '政治', '体育'], dtype='object')

In [39]:
#看array中的值
data.values

array([[44, 62, 53, 74, 56],
       [40, 90, 70, 59, 46],
       [60, 63, 50, 95, 43],
       [58, 43, 69, 96, 48],
       [78, 51, 71, 54, 57],
       [44, 62, 71, 61, 49],
       [96, 68, 99, 59, 79],
       [95, 49, 88, 89, 69],
       [74, 70, 45, 45, 66],
       [92, 54, 88, 82, 51]])

In [40]:
# 转置
data.T

同学0  同学1  同学2  同学3  同学4  同学5  同学6  同学7  同学8  同学9
语文   44   40   60   58   78   44   96   95   74   92
数学   62   90   63   43   51   62   68   49   70   54
英语   53   70   50   69   71   71   99   88   45   88
政治   74   59   95   96   54   61   59   89   45   82
体育   56   46   43   48   57   49   79   69   66   51

In [41]:
# 看前5行
data.head(5)

语文  数学  英语  政治  体育
同学0  44  62  53  74  56
同学1  40  90  70  59  46
同学2  60  63  50  95  43
同学3  58  43  69  96  48
同学4  78  51  71  54  57

## 2.3.1 修改行列索引值

In [45]:
stu = ["学生_" + str(i) for i in range(score_df.shape[0])]
data.index = stu
data
#不能单独修改索引中某个值
# data.index[3] = "学生_3" 是错误的

语文  数学  英语  政治  体育
学生_0  44  62  53  74  56
学生_1  40  90  70  59  46
学生_2  60  63  50  95  43
学生_3  58  43  69  96  48
学生_4  78  51  71  54  57
学生_5  44  62  71  61  49
学生_6  96  68  99  59  79
学生_7  95  49  88  89  69
学生_8  74  70  45  45  66
学生_9  92  54  88  82  51

## 2.3.2 重设索引
* reset_index(drop=False)
    * 设置新的下标索引
    * drop:默认False, 不删除元索引； True:删除原索引值

In [47]:
data.reset_index(drop=True)

语文  数学  英语  政治  体育
0  44  62  53  74  56
1  40  90  70  59  46
2  60  63  50  95  43
3  58  43  69  96  48
4  78  51  71  54  57
5  44  62  71  61  49
6  96  68  99  59  79
7  95  49  88  89  69
8  74  70  45  45  66
9  92  54  88  82  51

## 2.3.3 以某列值设置为新的索引
* set_index(keys,drop=True)
    * keys 行列索引名称
    * drop True当做新索引并删除原索引

In [49]:
df = pd.DataFrame({
    'month':[1,4,6,10],
    'year':[2012,2014,2013,2014],
    'sale':[55,40,84,31]
})
df

month  year  sale
0      1  2012    55
1      4  2014    40
2      6  2013    84
3     10  2014    31

In [50]:
# 设置 year为索引
df.set_index('year')

month  sale
year             
2012      1    55
2014      4    40
2013      6    84
2014     10    31

In [51]:
# 设置year和month为索引
df.set_index(['year','month'])

sale
year month      
2012 1        55
2014 4        40
2013 6        84
2014 10       31