In [3]:
import torch

x = torch.randn(1,3,4)
print(x.shape)
print(x)

torch.Size([1, 3, 4])
tensor([[[-1.0877, -1.1735, -0.5074, -1.4007],
         [-0.6383, -1.3518,  0.3953,  0.2265],
         [ 0.2643, -0.0876,  2.1618, -1.3398]]])


In [4]:
x.reshape(3,4,1)

tensor([[[-1.0877],
         [-1.1735],
         [-0.5074],
         [-1.4007]],

        [[-0.6383],
         [-1.3518],
         [ 0.3953],
         [ 0.2265]],

        [[ 0.2643],
         [-0.0876],
         [ 2.1618],
         [-1.3398]]])

In [6]:
x.transpose(2,0).transpose(0,1)

tensor([[[-1.0877],
         [-1.1735],
         [-0.5074],
         [-1.4007]],

        [[-0.6383],
         [-1.3518],
         [ 0.3953],
         [ 0.2265]],

        [[ 0.2643],
         [-0.0876],
         [ 2.1618],
         [-1.3398]]])